# Generated by Django 2.2.10 on 2020-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200515_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='evaluationquestion',
            name='evaluation',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='EvaluationAnswer',
        ),
        migrations.DeleteModel(
            name='EvaluationQuestion',
        ),
        migrations.DeleteModel(
            name='EvaluationScheme',
        ),
    ]
