# Generated by Django 2.2.10 on 2020-05-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
