# Generated by Django 2.2.10 on 2020-05-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_question_questionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
