# Generated by Django 2.2.10 on 2020-05-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_name', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.Questionnaire'),
        ),
    ]
