# Generated by Django 2.2.10 on 2020-05-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200515_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_name',
            field=models.CharField(max_length=100),
        ),
    ]
