# Generated by Django 2.2.10 on 2020-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='choice_id',
            field=models.IntegerField(default=True),
        ),
    ]
