# Generated by Django 2.2.10 on 2020-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_statistics_choice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='questionnaire_id',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='questions_id',
        ),
        migrations.AddField(
            model_name='statistics',
            name='choice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='statistics',
            name='questionnaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='statistics',
            name='questions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
