# Generated by Django 2.2.10 on 2020-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200516_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='user_id',
            field=models.IntegerField(default=True),
        ),
    ]
