# Generated by Django 2.2.10 on 2020-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200516_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
